name: Sync magazzino.csv from Google Sheets

on:
  schedule:
    - cron: '0 * * * *' # ogni ora
  workflow_dispatch: # consente anche l'esecuzione manuale

jobs:
  update-csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Scarica CSV da Google Sheets pubblicato
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vTpSPcmdbazc326rjW5oKXyXzD5I0ODXDWOhRunphN9ZpPFhHmsOo7AqgSGELt7O2jXFL7XNznSJL6z/pub?gid=961942791&single=true&output=csv" -o magazzino.csv

      - name: Configura git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit e push se ci sono modifiche
        run: |
          git add magazzino.csv
          git diff --cached --quiet || git commit -m "Aggiorna magazzino.csv da Google Sheets"
          git push